export const ADD_SHOES_SUCCESS = "ADD_SHOES_SUCCESS"
export const ADD_SHOES_FAIL = "ADD_SHOES_FAIL"

export const GET_SHOES_SUCCESS = "GET_SHOES_SUCCESS"
export const GET_SHOES_FAIL = "GET_SHOES_FAIL"


export const DELETE_SHOES_SUCCESS = "DELETE_SHOES_SUCCESS"
export const DELETE_SHOES_FAIL = "DELTEE_SHOES_FAIL"

export const UPDATE_SHOES_SUCCESS = "UPDATE_SHOES_SUCCESS"
export const UPDATE_SHOES_FAIL = "UPDATE_SHOES_FAIL"